"""Shared AI Gateway helper — single ``call_gateway_chat`` for extraction + QA.

Kept minimal: one function, no extra imports, no runtime deps beyond Gateway.
Monkeypatched by tests when they need to stub the model call.

The function is synchronous and optionally participates in the error-recovery
seam (spec 019): when a ``coordinator`` and ``recovery_ctx`` are supplied,
a failing ``gw.chat`` is handed to
``coordinator.handle_gateway_failure(...)`` which may fall back to an
alternate provider before the original error is re-raised. The async recovery
API is bridged with ``asyncio.run`` so the public signature stays sync for
existing callers (bilateral comparison, extraction, QA).
"""

from __future__ import annotations

import asyncio
import logging
from typing import TYPE_CHECKING, Any

from openreview_cli.gateway.models import CapabilityRequirement

if TYPE_CHECKING:
    from openreview_cli.recovery.coordinator import RecoveryCoordinator
    from openreview_cli.recovery.models import RecoveryContext

logger = logging.getLogger(__name__)

# Typed gateway error → HTTP status mapping for the recovery seam.
# Errors without a meaningful HTTP status map to None (unknown category).
_GATEWAY_ERROR_HTTP_STATUS: dict[type[Exception], int | None] = {}


def _register_status(exc_type: type[Exception], status: int | None) -> None:
    _GATEWAY_ERROR_HTTP_STATUS[exc_type] = status


def _init_status_map() -> None:
    """Populate the typed error→status map once (lazy import of gateway errors)."""
    if _GATEWAY_ERROR_HTTP_STATUS:
        return
    from openreview_cli.gateway.errors import (
        AllProvidersFailedError,
        AuthError,
        ConnectionError,
        ModelNotFoundError,
        NoMatchingProviderError,
        RateLimitError,
        UnclassifiedProviderError,
    )

    _register_status(RateLimitError, 429)
    _register_status(AuthError, 401)
    # R3-4: ConnectionError and UnclassifiedProviderError are transient →
    # recovery-layer provider_fallback. AllProvidersFailedError and
    # NoMatchingProviderError are terminal (None → unknown).
    _register_status(ConnectionError, 503)
    _register_status(UnclassifiedProviderError, 503)
    _register_status(ModelNotFoundError, 404)
    _register_status(AllProvidersFailedError, None)
    _register_status(NoMatchingProviderError, None)


def _http_status_for(exc: Exception) -> int | None:
    """Return the recovery HTTP status for a typed gateway error, else None."""
    _init_status_map()
    for exc_type, status in _GATEWAY_ERROR_HTTP_STATUS.items():
        if isinstance(exc, exc_type):
            return status
    return None


def call_gateway_chat(
    slot: str,
    messages: list[dict[str, str]],
    requirement: CapabilityRequirement | None = None,
    session_id: str | None = None,
    *,
    coordinator: RecoveryCoordinator | None = None,
    recovery_ctx: RecoveryContext | None = None,
    provider_list: list[str] | None = None,
) -> str:
    """Call the AI Gateway's chat method.

    Separated into its own function for testability (monkeypatching).

    Parameters
    ----------
    session_id:
        Optional session identifier for cost attribution.  When provided,
        all cost logs generated by this call will be queryable by this ID.
    coordinator:
        Optional recovery coordinator.  When supplied (with ``recovery_ctx``),
        a failed gateway call is routed through
        ``coordinator.handle_gateway_failure`` so the recovery framework can
        attempt provider fallback before the error propagates.
    recovery_ctx:
        Optional recovery context passed to the coordinator.
    provider_list:
        Optional ordered provider list used to seed the recovery context.
    """
    from openreview_cli.gateway.router import Gateway

    gw = Gateway()
    try:
        return gw.chat(slot, messages, requirement=requirement, session_id=session_id)
    except Exception as exc:
        if coordinator is None or recovery_ctx is None:
            raise

        # Seed the recovery context's provider list when the caller supplied
        # one but the shared context has none (e.g. direct-call tests).
        if provider_list and not recovery_ctx.provider_list:
            recovery_ctx.provider_list = list(provider_list)

        error_metadata: dict[str, Any] = {
            "http_status": _http_status_for(exc),
            "error_type": type(exc).__name__,
            "last_error": str(exc),
        }

        async def _recover(original_error: Exception = exc) -> str:
            recovered: dict[str, Any] = {}

            async def _retry_fn(provider: str) -> bool:
                """Re-invoke gw.chat with the alternate provider's model string."""
                try:
                    recovered["result"] = await asyncio.to_thread(
                        gw.chat,
                        slot,
                        messages,
                        requirement=requirement,
                        session_id=session_id,
                        model=provider,
                    )
                except Exception:
                    return False
                return True

            result = await coordinator.handle_gateway_failure(
                provider_name=slot,
                error_metadata=error_metadata,
                ctx=recovery_ctx,
                stage_name="review",
                attempt_fn=_retry_fn,
            )
            if result is None:
                # Recovery exhausted — surface the original failure.
                raise original_error
            # Recovery resolved via an alternate provider — return its result.
            return str(recovered["result"])

        return asyncio.run(_recover())
