name: Feature request
description: Suggest an idea for openreview-cli
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem are you solving?
      description: What's the use case?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What else have you tried or considered?
