"""Format renderers for memo export — Markdown, JSON, DOCX."""

from __future__ import annotations

import json
from dataclasses import asdict
from typing import TYPE_CHECKING, Any

from docx import Document as DocxDocument
from docx.oxml.ns import qn
from docx.shared import Pt

from openreview_cli.review.memo.models import MemoCitation

if TYPE_CHECKING:
    from openreview_cli.review.memo.models import MemoReport

# ── Colour-to-RGB mapping for DOCX cell fills (FR-04) ──

from openreview_cli.review.report import _confidence_bar

DISCLAIMER_TEXT = (
    "This memo was generated by an automated AI contract review tool. "
    "It is not legal advice and does not replace a qualified attorney's review. "
    "Always consult with legal counsel before making decisions based on this analysis."
)

G_A_R_RGB: dict[str, tuple[int, int, int]] = {
    "green": (198, 239, 206),
    "amber": (255, 235, 156),
    "red": (255, 199, 206),
}

G_A_R_EMOJI: dict[str, str] = {
    "green": "✅",
    "amber": "⚠️",
    "red": "❌",
}


# ── Helpers ──


def _citation_str(citation: Any) -> str:
    """Format a citation for display, or return a fallback."""
    if citation is None:
        return "Citation: not available"
    if isinstance(citation, MemoCitation):
        return f"Citation: {citation.clause_id} (paragraph {citation.paragraph_index})"
    # ponytail: plain-string fallback for legacy callers — remove when migration complete
    return f"Citation: {citation}"


def _truncate(text: str, limit: int = 10000) -> str:
    """Truncate *text* to *limit* chars, appending a note if cut."""
    if len(text) > limit:
        return text[:limit] + "\n\n... Truncated to 10,000 characters."
    return text


# ── Markdown Renderer ──


def render_markdown(memo: MemoReport) -> str:
    """Render a ``MemoReport`` as GitHub-Flavoured Markdown."""
    lines: list[str] = []

    # Header
    lines.append(f"# Memo Export: {memo.mode}")
    lines.append("")
    lines.append(f"**Document**: {memo.document_name}")
    lines.append(f"**Mode**: {memo.mode}")
    lines.append(f"**Review Date**: {memo.review_date}")
    lines.append(f"**Playbook**: {memo.playbook_name} (v{memo.playbook_version})")
    lines.append("")

    # Summary table
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Clauses Checked | {memo.overall.clauses_checked} |")
    lines.append(f"| Matches | {memo.overall.matches} |")
    lines.append(f"| Differences | {memo.overall.differences} |")
    lines.append(f"| Avg Confidence | {memo.overall.confidence_avg:.2f} |")
    lines.append(f"| Recommendation | **{memo.overall.recommendation.upper()}** |")
    if memo.overall.citation_relevance is not None:
        lines.append(f"| Citation Relevance | {memo.overall.citation_relevance:.2f} |")
    if memo.overall.citation_locality is not None:
        lines.append(f"| Citation Locality | {memo.overall.citation_locality:.2f} |")
    lines.append("")

    # Per-clause assessments
    lines.append("## Clause Assessments")
    lines.append("")

    if not memo.clauses:
        lines.append("No clauses to assess.")
        lines.append("")

    for clause in memo.clauses:
        emoji = G_A_R_EMOJI.get(clause.color, "❓")
        lines.append(f"### {emoji} {clause.id}: {clause.title}")
        lines.append("")
        lines.append(f"- **Assessment**: {clause.assessment}")
        lines.append(f"- **Color**: {clause.color}")
        lines.append(f"- **Confidence**: {_confidence_bar(clause.confidence)}")
        lines.append(f"- **Playbook Requirement**: {clause.playbook_requirement}")
        lines.append(f"- **Contract Text**: {_truncate(clause.contract_text)}")
        lines.append(f"- {_citation_str(clause.citation)}")
        if clause.severity:
            lines.append(f"- **Severity**: {clause.severity}")
        lines.append("")

    # Recommendation
    lines.append("## Recommendation")
    lines.append("")
    lines.append(f"**{memo.overall.recommendation.upper()}**")
    lines.append("")

    # Differences section
    lines.append("## Differences")
    lines.append("")
    if memo.overall.differences == 0:
        lines.append("No differences found.")
    else:
        lines.append(f"Found {memo.overall.differences} difference(s) requiring attention.")
    lines.append("")

    # Disclaimer
    lines.append("---")
    lines.append("")
    lines.append("*Disclaimer*")
    lines.append("")
    lines.append(DISCLAIMER_TEXT)

    # Playbook version footer
    lines.append("")
    lines.append("---")
    lines.append(f"*Playbook version: {memo.playbook_name} v{memo.playbook_version}*")
    lines.append("")

    return "\n".join(lines)


# ── JSON Renderer ──


def _memo_to_dict(memo: MemoReport) -> dict[str, Any]:
    """Convert a ``MemoReport`` to a JSON-serialisable dictionary."""
    base = asdict(memo)
    base["document"] = {"name": base.pop("document_name")}
    base["playbook"] = {
        "name": base.pop("playbook_name"),
        "version": base.pop("playbook_version"),
    }
    return base


def render_json(memo: MemoReport) -> str:
    """Render a ``MemoReport`` as a JSON string."""
    data = _memo_to_dict(memo)
    return json.dumps(data, indent=2, ensure_ascii=False)


# ── DOCX Renderer ──


def _add_doc_table(
    doc: Any,
    rows_data: list[tuple[str, str]],
    style: str = "Light Shading Accent 1",
) -> Any:
    """Create a 2-column table in *doc* from row data."""
    tbl = doc.add_table(rows=len(rows_data), cols=2)
    tbl.style = style
    for i, (label, value) in enumerate(rows_data):
        tbl.rows[i].cells[0].text = label
        tbl.rows[i].cells[1].text = value
    return tbl


def render_docx(memo: MemoReport) -> Any:
    """Render a ``MemoReport`` as a python-docx ``Document``.

    Returns the ``Document`` object (caller must save it).
    """
    doc = DocxDocument()

    def _add_citation_row(label: str, value: float | None) -> None:
        if value is not None:
            p = doc.add_paragraph()
            p.add_run(f"{label}: ").bold = True
            p.add_run(f"{value:.2f}")

    # ── Title ──
    doc.add_heading(f"Memo Export: {memo.mode}", level=1)

    # ── Header info ──
    for label, value in (
        ("Document:", memo.document_name),
        ("Mode:", memo.mode),
        ("Review Date:", memo.review_date),
        ("Playbook:", f"{memo.playbook_name} (v{memo.playbook_version})"),
    ):
        p = doc.add_paragraph()
        p.add_run(f"{label} ").bold = True
        p.add_run(value)

    doc.add_paragraph()  # spacer

    # ── Summary table ──
    doc.add_heading("Summary", level=2)
    _add_doc_table(
        doc,
        [
            ("Clauses Checked", str(memo.overall.clauses_checked)),
            ("Matches", str(memo.overall.matches)),
            ("Differences", str(memo.overall.differences)),
            ("Avg Confidence", f"{memo.overall.confidence_avg:.2f}"),
            ("Recommendation", memo.overall.recommendation.upper()),
        ],
    )
    _add_citation_row("Citation Relevance", memo.overall.citation_relevance)
    _add_citation_row("Citation Locality", memo.overall.citation_locality)

    doc.add_paragraph()  # spacer

    # ── Per-clause assessments ──
    doc.add_heading("Clause Assessments", level=2)

    if not memo.clauses:
        doc.add_paragraph("No clauses to assess.")
    else:
        for clause in memo.clauses:
            doc.add_heading(
                f"{G_A_R_EMOJI.get(clause.color, '❓')} {clause.id}: {clause.title}",
                level=3,
            )

            # Minimal info table (2 cols, 5 rows)
            tbl = _add_doc_table(
                doc,
                [
                    ("Assessment", clause.assessment),
                    ("Color", clause.color),
                    ("Confidence", f"{clause.confidence:.2f}"),
                    ("Playbook Requirement", clause.playbook_requirement),
                    ("Contract Text", _truncate(clause.contract_text)),
                ],
            )

            # Colour the color row cell
            rgb = G_A_R_RGB.get(clause.color)
            if rgb is not None:
                fill_hex = f"{rgb[0]:02X}{rgb[1]:02X}{rgb[2]:02X}"
                shading = tbl.rows[1].cells[1]._tc.get_or_add_tcPr()
                shading_elm = shading.makeelement(
                    qn("w:shd"),
                    {qn("w:fill"): fill_hex, qn("w:val"): "clear"},
                )
                shading.append(shading_elm)

            # Citation line as a separate paragraph
            cite_para = doc.add_paragraph(_citation_str(clause.citation))
            cite_para.style = doc.styles["Normal"]

            if clause.severity:
                sev_p = doc.add_paragraph()
                sev_p.add_run("Severity: ").bold = True
                sev_p.add_run(clause.severity)

            doc.add_paragraph()  # spacer between clauses

    # ── Recommendation ──
    doc.add_heading("Recommendation", level=2)
    rec_p = doc.add_paragraph()
    run = rec_p.add_run(memo.overall.recommendation.upper())
    run.bold = True
    run.font.size = Pt(14)

    # ── Differences ──
    doc.add_heading("Differences", level=2)
    if memo.overall.differences == 0:
        doc.add_paragraph("No differences found.")
    else:
        doc.add_paragraph(f"Found {memo.overall.differences} difference(s) requiring attention.")

    # ── Disclaimer ──
    doc.add_paragraph("─" * 50)
    disc_p = doc.add_paragraph()
    disc_p.add_run("Disclaimer").bold = True
    disc_para = doc.add_paragraph()
    run = disc_para.add_run(DISCLAIMER_TEXT)
    run.italic = True

    # Playbook version footer
    doc.add_paragraph()
    footer_p = doc.add_paragraph(f"Playbook version: {memo.playbook_name} v{memo.playbook_version}")
    footer_p.style = doc.styles["Normal"]

    return doc
