name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
      - run: uv sync --locked --no-dev
      - run: uv build
      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
      - run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
